[colors.primary]
  # Default colors
    background = '#ffffff'
    foreground = '#40466c'

  # Normal colors
[colors.normal]
    black =   '#484361'
    red =     '#f7a2a4'
    green =   '#9aa490'
    yellow =  '#bfae9b'
    blue =    '#8197c7'
    magenta = '#b1a5b9'
    cyan =    '#7081c5'
    white =   '#afafaf'

  # Bright colors
[colors.bright]
    black =   '#484361'
    red =     '#f7a2a4'
    green =   '#9aa490'
    yellow =  '#bfae9b'
    blue =    '#8197c7'
    magenta = '#b1a5b9'
    cyan =    '#c0c5d0'
    white =   '#afafaf'

