[colors.primary]
  # Default colors
    background = '0x0c0d0e'
    foreground = '0xb7b8b9'

  # Normal colors
[colors.normal]
    black =   '0x0c0d0e'
    red =     '0xe31a1c'
    green =   '0x31a354'
    yellow =  '0xdca060'
    blue =    '0x3182bd'
    magenta = '0x756bb1'
    cyan =    '0x80b1d3'
    white =   '0xb7b8b9'

  # Bright colors
[colors.bright]
    black =   '0x737475'
    red =     '0xe31a1c'
    green =   '0x31a354'
    yellow =  '0xdca060'
    blue =    '0x3182bd'
    magenta = '0x756bb1'
    cyan =    '0x80b1d3'
    white =   '0xfcfdfe'
