[colors.primary]
  # Default colors
    background = '0x1e1e1e'
    foreground = '0xaaa9a6'

  # Normal colors
[colors.normal]
    black =   '0x1e1e1e'
    red =     '0xcf8e85'
    green =   '0xb5b593'
    yellow =  '0xbdb292'
    blue =    '0x9891ad'
    magenta = '0xae98c1'
    cyan =    '0x9f97b2'
    white =   '0xf9fbff'

  # Bright colors
[colors.bright]
    black =   '0x736d6c'
    red =     '0xfcbab1'
    green =   '0xdcbfb8'
    yellow =  '0xebddb8'
    blue =    '0xc5c0da'
    magenta = '0xd6c3eb'
    cyan =    '0xc5c1db'
    white =   '0xffffff'

