# Colors (Monokai Pro)
[colors.primary]
  # Default colors
    background = '0x2c2525'
    foreground = '0xfff1f3'

  # Normal colors
[colors.normal]
    black =   '0x2c2525'
    red =     '0xfd6883'
    green =   '0xadda78'
    yellow =  '0xf9cc6c'
    blue =    '0xf38d70'
    magenta = '0xa8a9eb'
    cyan =    '0x85dacc'
    white =   '0xfff1f3'

  # Bright colors
[colors.bright]
    black =   '0x72696a'
    red =     '0xfd6883'
    green =   '0xadda78'
    yellow =  '0xf9cc6c'
    blue =    '0xf38d70'
    magenta = '0xa8a9eb'
    cyan =    '0x85dacc'
    white =   '0xfff1f3'

  # Dim colors
  #
  # If the dim colors are not set, they will be calculated automatically based
  # on the `normal` colors.
  # [colors.dim]
  #  black =   '0x000000'
  #  red =     '0x8c3336'
  #  green =   '0x7a8530'
  #  yellow =  '0x97822e'
  #  blue =    '0x506d8f'
  #  magenta = '0x80638e'
  #  cyan =    '0x497e7a'
  #  white =   '0x9a9a9a'

  # Indexed Colors
  #
  # The indexed colors include all colors from 16 to 256.
  # When these are not set, they're filled with sensible defaults.
  #
  # Example =
  #   `- { index = 16, color = '0xff00ff' }`
  #
  indexed_colors = []

# Visual Bell
#
# Any time the BEL code is received, Alacritty "rings" the visual bell. Once
# rung, the terminal background will be set to white and transition back to the
# default background color. You can control the rate of this transition by
# setting the `duration` property (represented in milliseconds). You can also
# configure the transition function by setting the `animation` property.
#
# Values for `animation` =
#   - Ease
#   - EaseOut
#   - EaseOutSine
#   - EaseOutQuad
#   - EaseOutCubic
#   - EaseOutQuart
#   - EaseOutQuint
#   - EaseOutExpo
#   - EaseOutCirc
#   - Linear
#
# Specifying a `duration` of `0` will disable the visual bell.
visual_bell =
  animation = EaseOutExpo
  duration = 0
  color = '0xffffff'
