import = ["/home/pansy/.config/alacritty/dark/ashes_dark.toml"]

[bell]
animation = "Linear"

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
dynamic_title = true
# opacity = 0.90

[window.padding]
x = 15
y = 15

[font]
size = 10

[font.normal]
family = "monospace"
style = "Regular"

# [font.bold]
# family = "Spleen"
# style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Shift|Control"

